// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ssklv/mixfood-menu-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MenuRepository is an autogenerated mock type for the MenuRepository type
type MenuRepository struct {
	mock.Mock
}

// CreateDish provides a mock function with given fields: ctx, dish
func (_m *MenuRepository) CreateDish(ctx context.Context, dish *domain.Dish) error {
	ret := _m.Called(ctx, dish)

	if len(ret) == 0 {
		panic("no return value specified for CreateDish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Dish) error); ok {
		r0 = rf(ctx, dish)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDish provides a mock function with given fields: ctx, id
func (_m *MenuRepository) DeleteDish(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllDishes provides a mock function with given fields: ctx
func (_m *MenuRepository) GetAllDishes(ctx context.Context) ([]*domain.Dish, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllDishes")
	}

	var r0 []*domain.Dish
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Dish, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Dish); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Dish)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDishByID provides a mock function with given fields: ctx, id
func (_m *MenuRepository) GetDishByID(ctx context.Context, id int64) (*domain.Dish, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDishByID")
	}

	var r0 *domain.Dish
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Dish, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Dish); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Dish)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDish provides a mock function with given fields: ctx, input
func (_m *MenuRepository) UpdateDish(ctx context.Context, input *domain.UpdateDishParams) (*domain.Dish, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDish")
	}

	var r0 *domain.Dish
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UpdateDishParams) (*domain.Dish, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UpdateDishParams) *domain.Dish); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Dish)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.UpdateDishParams) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMenuRepository creates a new instance of MenuRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMenuRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MenuRepository {
	mock := &MenuRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
