basePath: /
definitions:
  github_com_ssklv_mixfood-menu-service_internal_domain.Dish:
    properties:
      calories:
        type: integer
      carbs:
        type: number
      category:
        type: string
      created_at:
        type: string
      description:
        type: string
      fats:
        type: number
      id:
        type: integer
      image_url:
        type: string
      name:
        type: string
      price:
        type: number
      proteins:
        type: number
      updated_at:
        type: string
      volume:
        type: number
      weight:
        type: integer
    type: object
  github_com_ssklv_mixfood-menu-service_internal_domain.UpdateDishParams:
    properties:
      calories:
        type: integer
      carbs:
        format: float64
        type: number
      category:
        type: string
      description:
        type: string
      fats:
        format: float64
        type: number
      id:
        format: int64
        type: integer
      imageURL:
        type: string
      name:
        type: string
      price:
        format: float64
        type: number
      proteins:
        format: float64
        type: number
      volume:
        format: float64
        type: number
      weight:
        type: integer
    type: object
host: localhost:8082
info:
  contact: {}
  description: API для управления меню
  title: Mixfood Menu API
  version: "1.0"
paths:
  /api/menu:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_ssklv_mixfood-menu-service_internal_domain.Dish'
            type: array
      summary: Получить все блюда
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные блюда
        in: body
        name: dish
        required: true
        schema:
          $ref: '#/definitions/github_com_ssklv_mixfood-menu-service_internal_domain.Dish'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_ssklv_mixfood-menu-service_internal_domain.Dish'
      security:
      - BearerAuth: []
      summary: Создать блюдо
  /api/menu/{id}:
    delete:
      parameters:
      - description: ID блюда
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Удалить блюдо
    get:
      parameters:
      - description: ID блюда
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ssklv_mixfood-menu-service_internal_domain.Dish'
      summary: Получить блюдо по ID
    patch:
      consumes:
      - application/json
      parameters:
      - description: ID блюда
        in: path
        name: id
        required: true
        type: integer
      - description: Параметры обновления
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/github_com_ssklv_mixfood-menu-service_internal_domain.UpdateDishParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ssklv_mixfood-menu-service_internal_domain.Dish'
      security:
      - BearerAuth: []
      summary: Обновить блюдо
  /api/menu/upload:
    post:
      parameters:
      - description: Изображение
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Загрузить изображение
securityDefinitions:
  CookieAuth:
    in: cookie
    name: jwt
    type: apiKey
swagger: "2.0"
