basePath: /
definitions:
  github_com_ssklv_mixfood-menu-service_internal_domain.Dish:
    properties:
      calories:
        type: integer
      carbs:
        type: number
      categoryId:
        type: integer
      createdAt:
        type: string
      description:
        type: string
      fats:
        type: number
      id:
        type: integer
      imageUrl:
        type: string
      name:
        type: string
      price:
        type: number
      proteins:
        type: number
      updatedAt:
        type: string
      volume:
        type: number
      weight:
        type: integer
    type: object
  github_com_ssklv_mixfood-menu-service_internal_domain.UpdateDishParams:
    properties:
      calories:
        type: integer
      carbs:
        type: number
      categoryId:
        type: integer
      description:
        type: string
      fats:
        type: number
      imageUrl:
        type: string
      name:
        type: string
      price:
        type: number
      proteins:
        type: number
      volume:
        type: number
      weight:
        type: integer
    type: object
  internal_handlers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost:8082
info:
  contact: {}
  description: API для управления категориями и блюдами меню
  title: Mixfood Menu Service API
  version: "1.0"
paths:
  /api/menu:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_ssklv_mixfood-menu-service_internal_domain.Dish'
            type: array
      summary: Получить все блюда
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные создаваемого блюда
        in: body
        name: dish
        required: true
        schema:
          $ref: '#/definitions/github_com_ssklv_mixfood-menu-service_internal_domain.Dish'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_ssklv_mixfood-menu-service_internal_domain.Dish'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_handlers.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Создать новое блюдо
  /api/menu/{id}:
    delete:
      parameters:
      - description: Идентификатор блюда
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Удалить блюдо из меню
    get:
      parameters:
      - description: Идентификатор блюда
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ssklv_mixfood-menu-service_internal_domain.Dish'
      summary: Получить блюдо по ID
    patch:
      consumes:
      - application/json
      parameters:
      - description: Идентификатор блюда
        in: path
        name: id
        required: true
        type: integer
      - description: Поля для обновления
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/github_com_ssklv_mixfood-menu-service_internal_domain.UpdateDishParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ssklv_mixfood-menu-service_internal_domain.Dish'
      security:
      - BearerAuth: []
      summary: Обновить параметры блюда
  /api/menu/upload:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Файл изображения
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Загрузить изображение
securityDefinitions:
  BearerAuth:
    description: 'Введите токен в формате: Bearer <token>'
    in: header
    name: Authorization
    type: apiKey
  CookieAuth:
    description: Токен доступа (access_token), автоматически извлекаемый из Cookie
    in: cookie
    name: access_token
    type: apiKey
swagger: "2.0"
